DROP DATABASE IF EXISTS pillsDB;
CREATE database pillsDB;

USE pillsDB;

CREATE TABLE Mind_Ex (
  id Int( 100 ) AUTO_INCREMENT NOT NULL,
  Name VARCHAR(100) NOT NULL,
  Details VARCHAR(300) NOT NULL,
  PRIMARY KEY(ID)
);